FROM ubuntu:20.04
RUN apt-get update && \
    apt-get install -y wget tar && \
    wget https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz && \
    tar -xvzf prometheus-2.52.0.linux-amd64.tar.gz && \
    mv prometheus-2.52.0.linux-amd64 /prometheus

EXPOSE 9090
CMD ["/prometheus/prometheus", "--config.file=/prometheus/prometheus.yml"]
