global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'microservice'
    metrics_path: /metrics
    static_configs:
      - targets: ['172.17.0.1:5000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.17.0.1:9100']

